spring:
  application:
    name: gur-bot
  main:
    banner-mode: off
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      format_sql: true
  datasource:
    platform: postgres
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    gur.bot: INFO

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}